# This file aims to provide an example of recording from huateng_camera 
# with advanced settings.
# Generated by Google gemini flash 2.5 

import sys
import time
import numpy as np
import cv2 # For preview
import threading
import queue # For communication between preview thread and main thread (optional)
from typing import Optional, Tuple

# Import necessary classes from existing files
import camera.mvsdk as mvsdk
from camera.huateng_camera_tc import Camera, enumerate_cameras, APPENDED_ROWS_FOR_TIMECODE # Import APPENDED_ROWS_FOR_TIMECODE
from CameraSystem import CameraSystem
from encoders.x264_encoder_x264 import X264Encoder
from analyzers.nnanalyzer import NNAnalyzer # Or a specific analyzer like SleapAnalyzer
from analyzers.sleap_analyzer import SleapAnalyzer # Import SleapAnalyzer explicitly
from ringbuffer.shared_ring_buffer import ProcessSafeSharedRingBuffer # Needed for cleanup

# Configuration (can be loaded from file or command line args)
# Example configuration structure
config = {
    'camera': {
        'device_index': 0, # Or use enumeration
        'exposure_time_ms': 16.666, # Example
        'timecode_enabled': True,
        # Add more SDK settings here later
    },
    'analyzer': {
        'class': 'SleapAnalyzer', # Specify analyzer class name
        'needs_timecode': True,
        'model_path': 'nntest/best_model.h5',
        'padding_target_shape': (1024, 1280),
        'model_input_shape': (512, 640),
        # Add other analyzer specific configs
    },
    'video_encoder': {
        'class': 'X264Encoder', # Specify encoder class name
        'output_path': 'advanced_recording_output.mp4',
        'batch_size': 30,
        'fps': 60, # Target FPS for encoding (can be different from camera FPS)
        'preset': 'fast',
        'crf': 23,
        'threads': 0,
        'rc_lookahead': 60,
        # Add other encoder specific configs
    },
    'buffer_capacity': 600,
    'preview': {
        'enabled': True,
        'window_name': 'Camera Preview',
        'display_interval_ms': 30, # Interval to update preview window
    }
}

# Global flags and objects for recording control
is_recording = False
camera_system: Optional[CameraSystem] = None
camera: Optional[Camera] = None
# analyzer and encoder instances are managed by CameraSystem, access via camera_system.analyzer/video_encoder
shared_buffer: Optional[ProcessSafeSharedRingBuffer] = None # Keep reference for cleanup


def start_recording(config):
    global is_recording, camera_system, camera, shared_buffer

    if is_recording:
        print("Recording is already in progress.")
        return

    print("Starting recording...")
    is_recording = True

    try:
        # --- Initialize Camera ---
        dev_list = mvsdk.CameraEnumerateDevice()
        if not dev_list:
            print("No cameras found. Cannot start recording.")
            is_recording = False
            return

        # Select camera based on config (e.g., index 0)
        dev_info = dev_list[config['camera']['device_index']]
        camera = Camera(
            dev_info,
            exposure_time_ms=config['camera']['exposure_time_ms'],
            tc=config['camera']['timecode_enabled']
            # Pass additional camera settings from config here
        )
        if not camera.open():
            print("Failed to open camera. Cannot start recording.")
            is_recording = False
            camera = None # Ensure camera is None if open fails
            return

        # --- Determine Original Frame Shape (for config) ---
        try:
            original_width = camera.width
            original_height = camera.height
            channels = camera.channels
            output_frame_height = camera.output_frame_height # Height with timecode space
            original_frame_shape = (original_height, original_width, channels)
            output_frame_shape = (output_frame_height, original_width, channels) # Full buffer frame shape
            print(f"Main: Original camera frame HxWxC: {original_height}x{original_width}x{channels}")
            print(f"Main: Output frame H'xWxC (with timecode space): {output_frame_shape}")
        except AttributeError:
            print("Main: Warning: Camera object does not provide full shape info. Using defaults for config.")
            # Use defaults or raise error if critical
            original_height, original_width, channels = 1024, 1280, 3 # Example defaults
            original_frame_shape = (original_height, original_width, channels)
            output_frame_shape = (original_height + APPENDED_ROWS_FOR_TIMECODE, original_width, channels)


        # --- Prepare Analyzer and Encoder Configurations ---
        # Analyzer config needs frame_shape (buffer shape) and effective_image_shape (original)
        analyzer_config = config['analyzer'].copy() # Use a copy to avoid modifying the original config dict
        analyzer_config['frame_shape'] = output_frame_shape # Analyzer might need full frame for TC
        analyzer_config['effective_image_shape'] = original_frame_shape # Analyzer needs original image shape
        analyzer_config['timecode_timebase'] = camera.timecode_timebase # Pass camera's timebase

        # Video Encoder config needs frame_size (original image size)
        video_encoder_config = config['video_encoder'].copy() # Use a copy
        video_encoder_config['frame_size'] = original_frame_shape # Encoder expects original frame size
        video_encoder_config['camera_fps'] = camera.actual_fps # Pass actual camera FPS
        video_encoder_config['timebase'] = camera.timecode_timebase # Pass camera's timebase


        # --- Instantiate CameraSystem ---
        print("Creating CameraSystem instance...")
        # CameraSystem will manage the capture and snapshot threads,
        # but Analyzer and Encoder processes are started/stopped externally.
        # CameraSystem.__init__ instantiates Analyzer and VideoEncoder internally.
        camera_system = CameraSystem(
            camera=camera,
            AnalyzerClass=globals().get(analyzer_config.pop('class', 'NNAnalyzer'), NNAnalyzer), # Get class by name, default to NNAnalyzer
            VideoEncoderClass=globals().get(video_encoder_config.pop('class', 'X264Encoder'), X264Encoder), # Get class by name, default to X264Encoder
            analyzer_config=analyzer_config, # Pass remaining config
            video_encoder_config=video_encoder_config, # Pass remaining config
            buffer_capacity=config['buffer_capacity'] # Pass buffer capacity
        )
        print("CameraSystem instance created.")

        # --- Start Components (Managed Externally by CameraSystem) ---
        # Start order: Analyzer and Encoder processes first, then CameraSystem threads
        print("Starting Analyzer process...")
        camera_system.analyzer.start() # Start the process managed by CameraSystem
        print("Starting VideoEncoder process...")
        camera_system.video_encoder.start() # Start the process managed by CameraSystem
        print("Starting CameraSystem internal threads...")
        camera_system.start() # Starts capture and snapshot threads

        print("Recording started. Press 'q' to stop and quit.")
        # Main thread can now wait for stop signal or user input

    except Exception as e:
        print(f"Error during recording startup: {e}")
        import traceback
        traceback.print_exc()
        # Ensure cleanup if startup fails
        stop_recording() # Call stop_recording to handle partial initialization cleanup


def stop_recording():
    global is_recording, camera_system, camera, shared_buffer

    if not is_recording:
        print("No recording in progress.")
        return

    print("Stopping recording...")
    is_recording = False # Signal threads to stop

    # --- Stop Components in Correct Order ---
    # Stop order: CameraSystem internal threads, then Analyzer/Encoder processes, then CameraSystem resources, then Camera.
    
    # 1. Stop CameraSystem internal threads (capture/snapshot)
    if camera_system:
        print("Stopping CameraSystem internal threads...")
        camera_system.stop() # Stops capture/snapshot threads

    # 2. Stop Analyzer and Encoder processes first
    # Use the references held by camera_system
    if camera_system and camera_system.analyzer:
        print("Stopping Analyzer process...")
        camera_system.analyzer.stop()
    if camera_system and camera_system.video_encoder:
        print("Stopping VideoEncoder process...")
        camera_system.video_encoder.stop()

    # 3. Clean up CameraSystem resources (shared buffer)
    # CameraSystem.close() handles the buffer cleanup
    if camera_system:
        print("Closing CameraSystem resources (shared buffer)...")
        camera_system.close() # Closes and unlinks buffer
        camera_system = None # Clear reference

    # 4. Close Camera hardware
    if camera:
        print("Closing camera hardware...")
        camera.close()
        print(f"Camera captured {camera.frames_captured} frames.")
        camera = None # Clear reference

    # 5. Clean up shared buffer reference if it wasn't managed by CameraSystem (shouldn't happen with current plan)
    # If shared_buffer was created directly in start_recording and not passed to CameraSystem for management,
    # we would need to close/unlink it here. But with the current plan, CameraSystem manages it.
    # if shared_buffer:
    #     print("Cleaning up shared buffer directly...")
    #     try:
    #         shared_buffer.close()
    #         shared_buffer.unlink()
    #     except Exception as e:
    #         print(f"Error cleaning up shared buffer directly: {e}")
    #     finally:
    #         shared_buffer = None


    print("Recording stopped and resources cleaned up.")


def main():
    global is_recording, camera_system, camera, shared_buffer # Need to access/modify globals

    print("Advanced Recording Program")
    print("Press 's' to start recording.")
    print("Press 'q' to quit.")

    window_name = config['preview']['window_name']
    display_interval_ms = config['preview']['display_interval_ms']

    # Create the preview window in the main thread
    if config['preview']['enabled']:
        cv2.namedWindow(window_name)
        print(f"Preview window '{window_name}' created. Waiting for start signal.")

    # Main loop for handling preview and key presses
    while config['preview']['enabled'] and cv2.getWindowProperty(window_name, cv2.WND_PROP_VISIBLE) >= 1: # Loop while window is open and preview is enabled
        combined_frame = None # Initialize combined_frame for the sleep check later

        if is_recording and camera_system and camera_system.shared_buffer: # Only try to get frame if recording and buffer exists
            combined_frame = camera_system.shared_buffer.peek_last_frame()

            if combined_frame is not None:
                # Process and display the frame (same logic as before)
                # Get original shape from camera instance, which is available if recording started successfully
                original_height, original_width, channels = camera.height, camera.width, camera.channels
                buffer_frame_height = combined_frame.shape[0]

                if buffer_frame_height > original_height:
                    image_for_preview = combined_frame[:original_height, :, :]
                else:
                    image_for_preview = combined_frame

                cv2.imshow(window_name, image_for_preview)
            # else:
                # print("Main loop: No frame available in buffer.") # Optional debug

        # Handle key presses and update window
        key = cv2.waitKey(display_interval_ms) & 0xFF

        if key == ord('s') and not is_recording:
            start_recording(config)
        elif key == ord('q'):
            print("Quit signal received.")
            if is_recording:
                stop_recording()
            break # Exit main loop

        # Add a small sleep if not recording and no frame was processed, to avoid high CPU usage
        # waitKey provides some waiting, but an explicit sleep might be needed if display_interval_ms is small
        # Only sleep if not recording AND no frame was displayed in this iteration
        if not is_recording and combined_frame is None:
             time.sleep(0.01)

    # If preview is disabled, the loop above won't run.
    # We still need a way to start/stop recording and quit.
    # For simplicity now, we'll assume preview is always enabled for key control.
    # A more advanced version could use a different input method if preview is off.
    if not config['preview']['enabled']:
         print("Preview is disabled. No key press handling in this mode.")
         print("Program will exit after a short delay.")
         time.sleep(2) # Give user time to read message


    print("Program exiting.")
    # Ensure all resources are cleaned up on exit
    stop_recording() # Call stop again just in case
    cv2.destroyAllWindows() # Ensure preview window is closed

if __name__ == "__main__":
    main()
