# test_shared_ring_buffer_v2a.py
# Generated by Claude Sonnet 4.6
#
# Reuses ALL test cases from test_shared_ring_buffer.py (v2 baseline),
# with the import changed to v2a. Additionally adds three pickle-specific
# test cases that validate the new __getstate__/__setstate__ protocol.
#
# Run:
#   pytest tests/test_shared_ring_buffer_v2a.py -v

import pytest
import numpy as np
import multiprocessing as mp
import multiprocessing.shared_memory as mp_shm
import time
from ringbuffers.shared_ring_buffer_v2a import ProcessSafeSharedRingBuffer  # ← v2a

# Define buffer parameters for testing
BUFFER_CAPACITY = 5
FRAME_SHAPE = (10, 20, 3) # Example frame size (height, width, channels)
FRAME_DTYPE = np.dtype('uint8')
FRAME_BYTES = int(np.prod(FRAME_SHAPE) * FRAME_DTYPE.itemsize)

@pytest.fixture
def shared_buffer():
    """Fixture to create and unlink the shared ring buffer."""
    buffer = ProcessSafeSharedRingBuffer(create=True, buffer_capacity=BUFFER_CAPACITY, frame_shape=FRAME_SHAPE, dtype=FRAME_DTYPE)
    yield buffer
    buffer.close()
    buffer.unlink()

def create_dummy_frame(value, shape=FRAME_SHAPE, dtype=FRAME_DTYPE):
    """Helper function to create a dummy frame."""
    return np.full(shape, value, dtype=dtype)

import random

def create_dummy_frames(start_value, num_frames, shape=FRAME_SHAPE, dtype=FRAME_DTYPE, use_random=False, random_seed=None):
    """Helper function to create multiple dummy frames."""
    frames = np.zeros((num_frames,) + shape, dtype=dtype)
    if use_random:
        dtype_info = np.iinfo(dtype)
        for i in range(num_frames):
            effective_value = start_value + i
            # Use a combination of random_seed and effective_value for reproducibility
            seed = random_seed + effective_value if random_seed is not None else effective_value
            rng = np.random.default_rng(seed)
            # Generate a single random value for this frame
            random_value = rng.integers(low=dtype_info.min, high=dtype_info.max + 1, size=1, dtype=dtype)[0]
            frames[i] = create_dummy_frame(random_value, shape, dtype)
    else:
        for i in range(num_frames):
            frames[i] = create_dummy_frame(start_value + i, shape, dtype)
    return frames

# =============================================================================
# Re-used v2 tests (unchanged logic, import already points to v2a above)
# =============================================================================

def test_basic_put_get(shared_buffer):
    """Test basic put and get operations."""
    frame1 = create_dummy_frames(1, 1)
    frame2 = create_dummy_frames(2, 1)

    assert shared_buffer.put(frame1) is True
    assert shared_buffer.put(frame2) is True

    # Get the first frame
    frames_list = shared_buffer.get(1)
    assert frames_list is not None
    assert len(frames_list) == 1
    retrieved_frame1 = frames_list[0]
    assert np.array_equal(retrieved_frame1, frame1)

    # Get the second frame
    frames_list = shared_buffer.get(1)
    assert frames_list is not None
    assert len(frames_list) == 1
    retrieved_frame2 = frames_list[0]
    assert np.array_equal(retrieved_frame2, frame2)

    # Test getting more frames than available (should block or timeout in a real scenario,
    # but in this basic test, it should return None immediately if no data)
    frames_list = shared_buffer.get(1, timeout=0.1) # Use a small timeout
    assert frames_list is None

def test_put_get_multiple_frames(shared_buffer):
    """Test putting and getting multiple frames at once."""
    # Put multiple frames
    frames_to_put = create_dummy_frames(0, 3)
    assert shared_buffer.put(frames_to_put) is True

    # Get multiple frames
    frames_list = shared_buffer.get(2)
    assert frames_list is not None
    assert len(frames_list) == 1
    assert np.array_equal(frames_list[0], create_dummy_frames(0, 2))

    # Put more frames, causing wrap around
    shared_buffer.release_last_got_data() 
    frames_to_put_2 = create_dummy_frames(3, 4) # 3 + 4 = 7 > 5, wraps
    assert shared_buffer.put(frames_to_put_2) is True

    # Get remaining frames, causing wrap around
    frames_list = shared_buffer.get(5) # 3 frames were put initially, 2 were retrieved, 1 remains. Then 4 were put. Total 5 remaining.
    assert frames_list is not None
    assert len(frames_list) == 2 # Should wrap around

    retrieved_frames = np.concatenate(frames_list, axis=0)
    # Expected frames: the remaining 1 from the first put, then the 4 from the second put.
    expected_frames = np.concatenate((create_dummy_frames(2, 1), create_dummy_frames(3, 4)), axis=0)
    assert np.array_equal(retrieved_frames, expected_frames)

def test_buffer_full(shared_buffer):
    """Test putting frames when the buffer is full."""
    # Fill the buffer
    frames_to_put = create_dummy_frames(0, BUFFER_CAPACITY)
    assert shared_buffer.put(frames_to_put) is True

    # Try to put one more frame, should time out
    start_time = time.time()
    assert shared_buffer.put(create_dummy_frames(BUFFER_CAPACITY, 1), timeout=0.5) is False
    end_time = time.time()
    assert end_time - start_time >= 0.5

def test_buffer_empty(shared_buffer):
    """Test getting frames when the buffer is empty."""
    # Try to get a frame from an empty buffer, should time out
    start_time = time.time()
    frames_list = shared_buffer.get(1, timeout=0.5)
    end_time = time.time()
    assert frames_list is None
    assert end_time - start_time >= 0.5

    # Put a frame and then get it
    frame = create_dummy_frames(0, 1)
    assert shared_buffer.put(frame) is True
    frames_list = shared_buffer.get(1, timeout=0.5)
    assert frames_list is not None
    assert len(frames_list) == 1
    assert np.array_equal(frames_list[0], frame)

    # Try to get another frame, should time out again
    start_time = time.time()
    frames_list = shared_buffer.get(1, timeout=0.5)
    end_time = time.time()
    assert frames_list is None
    assert end_time - start_time >= 0.5

def test_release_last_got_data(shared_buffer):
    """Test the _release_last_got_data method."""

    # Fill the buffer
    assert shared_buffer.put(create_dummy_frames(0, BUFFER_CAPACITY)) is True

    # Get some frames (space not released yet)
    frames_list = shared_buffer.get(2)
    assert frames_list is not None

    # Now, try to put a frame. This should block because the buffer is logically full
    start_time = time.time()
    assert shared_buffer.put(create_dummy_frames(BUFFER_CAPACITY, 1), timeout=0.5) is False
    end_time = time.time()
    assert end_time - start_time >= 0.5

    # Now, perform another get. This should trigger the release of the space for the first 2 frames.
    frames_list = shared_buffer.get(1) # Get one more frame
    assert frames_list is not None

    # After this get, the space for the first 2 frames should be released.
    assert shared_buffer.put(create_dummy_frames(BUFFER_CAPACITY + 1, 1), timeout=0.5) is True

def test_wrap_around_put(shared_buffer):
    """Test putting frames that wrap around the buffer."""
    # Put frames to fill the buffer partially
    assert shared_buffer.put(create_dummy_frames(0, BUFFER_CAPACITY - 2)) is True

    # Get some frames to move the read pointer
    frames_list = shared_buffer.get(2)
    assert frames_list is not None
    assert len(frames_list) == 1 # Should return a single view if no wrap around on get
    assert np.array_equal(frames_list[0], create_dummy_frames(0, 2))

    # Release occupation
    shared_buffer.release_last_got_data()
    # Put frames that will wrap around
    frames_to_put = create_dummy_frames(BUFFER_CAPACITY - 2, 3) # 3 frames, capacity is 5, 3 + (5-2) = 6 > 5, so it wraps
    assert shared_buffer.put(frames_to_put) is True

    # Get all frames and check their order
    frames_list = shared_buffer.get(4)
    assert frames_list is not None
    assert len(frames_list) == 2 # Should return two views due to wrap around on get

    # Concatenate the views to check the full sequence
    retrieved_frames = np.concatenate(frames_list, axis=0)
    expected_frames = np.concatenate((create_dummy_frames(2, 3), create_dummy_frames(5, 1)), axis=0) # Expected order after wrap around
    assert np.array_equal(retrieved_frames, expected_frames)


def test_wrap_around_get(shared_buffer):
    """Test getting frames that wrap around the buffer."""
    # Fill the buffer
    assert shared_buffer.put(create_dummy_frames(0, BUFFER_CAPACITY)) is True

    # Get 3 frames, read_ptr is 0, capacity is 5. 0 + 3 = 3 < 5, no wrap yet.
    frames_list = shared_buffer.get(3)
    assert frames_list is not None
    assert len(frames_list) == 1
    assert np.array_equal(frames_list[0], create_dummy_frames(0, 3))

    # Release occupation
    shared_buffer.release_last_got_data()
    # Put 2 more frames to ensure enough data for wrap-around get
    assert shared_buffer.put(create_dummy_frames(5, 2)) is True # Put frames 5 and 6
    # Get 3 frames, which should cause wrap around. read_ptr is 3. 3 + 3 = 6 > 5, wraps around.
    frames_list = shared_buffer.get(3)
    assert frames_list is not None
    assert len(frames_list) == 2 # Should return two views due to wrap around on get

    # Concatenate the views to check the full sequence
    retrieved_frames = np.concatenate(frames_list, axis=0)
    expected_frames = np.concatenate((create_dummy_frames(3, 2), create_dummy_frames(5, 1)), axis=0) # Expected frames: 3, 4, 5
    assert np.array_equal(retrieved_frames, expected_frames)

def producer_task(source_buffer, num_frames_to_put, frame_shape, frame_dtype):
    """Task for a producer process (uses deprecated attach mode for backward compat)."""
    try:
        buffer = ProcessSafeSharedRingBuffer(create=False, source_buffer=source_buffer)
        for i in range(num_frames_to_put):
            frames = create_dummy_frames(i, 1, shape=frame_shape, dtype=frame_dtype)
            if not buffer.put(frames, timeout=5.0):
                print(f"Producer: Timeout putting frame {i}")
                break
        buffer.close()
    except Exception as e:
        print(f"Producer process error: {e}")
        raise

def consumer_task(source_buffer, num_frames_to_get, frame_shape, frame_dtype, results_queue):
    """Task for a consumer process (uses deprecated attach mode for backward compat)."""
    try:
        buffer = ProcessSafeSharedRingBuffer(create=False, source_buffer=source_buffer)
        retrieved_frames = []
        for i in range(num_frames_to_get):
            frames_list = buffer.get(1, timeout=5.0)
            if frames_list is not None:
                frames = np.concatenate(frames_list, axis=0).copy() # Deep copy to persist the data
                retrieved_frames.append(frames)
            else:
                print(f"Consumer: Timeout getting frame {i}")
                break
        all_frames = np.concatenate(retrieved_frames, axis=0)
        print(f"Consumer putting frames to queue, of a total memory size: {all_frames.nbytes} Bytes")
        results_queue.put(retrieved_frames)
        buffer.close()
    except Exception as e:
        print(f"Consumer process error: {e}")
        raise


def test_process_safety(shared_buffer):
    """Test concurrent put and get operations from multiple processes."""
    mp.set_start_method('spawn', force=True) # Use spawn method for better compatibility

    num_frames = BUFFER_CAPACITY * 2 # Put and get more frames than capacity

    # Use a Queue to get results from the consumer process
    results_queue = mp.Queue(maxsize=1)

    # Create producer and consumer processes
    producer_p = mp.Process(target=producer_task, args=(shared_buffer, num_frames, FRAME_SHAPE, FRAME_DTYPE))
    consumer_p = mp.Process(target=consumer_task, args=(shared_buffer, num_frames, FRAME_SHAPE, FRAME_DTYPE, results_queue))

    # Start processes
    producer_p.start()
    consumer_p.start()

    # Get results from the consumer
    retrieved_frames_list = results_queue.get()
    retrieved_frames = np.concatenate(retrieved_frames_list, axis=0, dtype=FRAME_DTYPE)

    # Wait for processes to finish
    producer_p.join()
    consumer_p.join()
    
    print(f"Retrieved frames shape: {retrieved_frames.shape}")
    print(f"Expected {num_frames} frames, got {len(retrieved_frames)}")

    # Verify the retrieved frames
    expected_frames = create_dummy_frames(0, num_frames, shape=FRAME_SHAPE, dtype=FRAME_DTYPE)

    assert len(retrieved_frames) == num_frames, f"Expected {num_frames} frames, got {len(retrieved_frames)}"

    retrieved_set = set(tuple(frame.tobytes()) for frame in retrieved_frames)
    expected_set = set(tuple(frame.tobytes()) for frame in expected_frames)
    assert retrieved_set == expected_set, "Retrieved frames do not match expected frames"


def test_invalid_frame_put(shared_buffer):
    """Test putting frames with invalid size or dtype."""
    # Test invalid shape
    invalid_shape_frame = np.zeros((1,) + (10, 20, 4), dtype=FRAME_DTYPE) # Wrong channel count
    assert shared_buffer.put(invalid_shape_frame) is False

    # Test invalid dtype
    invalid_dtype_frame = np.zeros((1,) + FRAME_SHAPE, dtype=np.float32) # Wrong dtype
    assert shared_buffer.put(invalid_dtype_frame) is False

    # Ensure no frames were actually put
    frames_list = shared_buffer.get(1, timeout=0.1)
    assert frames_list is None


def test_close_and_unlink(shared_buffer):
    """Test closing and unlinking the shared memory."""
    metadata_name = shared_buffer.metadata_name
    data_name = shared_buffer.data_name

    buffer = ProcessSafeSharedRingBuffer(create=True, buffer_capacity=BUFFER_CAPACITY, frame_shape=FRAME_SHAPE, dtype=FRAME_DTYPE)
    metadata_name = buffer.metadata_name
    data_name = buffer.data_name

    buffer.close()
    buffer.unlink()

    # After unlinking, trying to access by name should fail.
    with pytest.raises(FileNotFoundError):
        mp_shm.SharedMemory(name=metadata_name)
    with pytest.raises(FileNotFoundError):
        mp_shm.SharedMemory(name=data_name)

    # Ensure internal references are cleared after unlink
    assert buffer._metadata_shm is None
    assert buffer._data_shm is None


def test_peek_last_frame_basic(shared_buffer):
    """Test basic peek_last_frame operations."""
    # 1. Peek empty buffer
    assert shared_buffer.peek_last_frame() is None, "Peek on empty buffer should return None"

    # 2. Put one frame and peek
    frame0 = create_dummy_frames(0, 1)
    assert shared_buffer.put(frame0) is True
    peeked0 = shared_buffer.peek_last_frame()
    assert peeked0 is not None, "Peek after first put returned None"
    assert np.array_equal(peeked0, frame0[0]), "Peeked frame 0 content mismatch"
    # Ensure it's a copy
    peeked0_copy = peeked0.copy()
    peeked0_copy[0, 0, 0] = 99 # Modify the peeked frame copy
    peeked0_again = shared_buffer.peek_last_frame() # Peek again
    assert peeked0_again is not None
    assert peeked0_again[0, 0, 0] == 0, "Original buffer data changed after modifying peeked copy"
    assert not np.array_equal(peeked0_copy, peeked0_again), "Modified copy should differ from fresh peek"

    # 3. Put another frame and peek
    frame1 = create_dummy_frames(1, 1)
    assert shared_buffer.put(frame1) is True
    peeked1 = shared_buffer.peek_last_frame()
    assert peeked1 is not None, "Peek after second put returned None"
    assert np.array_equal(peeked1, frame1[0]), "Peeked frame 1 content mismatch"

    # 4. Ensure read/write pointers and counts are unchanged by peek
    with shared_buffer.pointer_lock:
        read_ptr_before, write_ptr_before, occupied_before, last_get_before = shared_buffer._get_pointers_metadata()

    shared_buffer.peek_last_frame() # Perform the peek

    with shared_buffer.pointer_lock:
        read_ptr_after, write_ptr_after, occupied_after, last_get_after = shared_buffer._get_pointers_metadata()

    assert read_ptr_before == read_ptr_after, "Read pointer changed after peek"
    assert write_ptr_before == write_ptr_after, "Write pointer changed after peek"
    assert occupied_before == occupied_after, "Occupied count changed after peek"
    assert last_get_before == last_get_after, "Last get count changed after peek"


def test_peek_last_frame_after_get_no_release(shared_buffer):
    """Test peeking after get() without explicit release, covering user scenarios."""
    frames_initial = create_dummy_frames(0, 3) # F0, F1, F2
    assert shared_buffer.put(frames_initial) is True

    # --- Scenario A: Get 2 frames (like get(2)) ---
    print("\nScenario A: get(2)")
    got_list_1 = shared_buffer.get(2) # Gets F0, F1
    assert got_list_1 is not None
    assert len(got_list_1) == 1
    assert np.array_equal(got_list_1[0], frames_initial[:2])

    # Peek after getting 2 (last put was F2)
    peeked_after_get2 = shared_buffer.peek_last_frame()
    assert peeked_after_get2 is not None, "Peek after get(2) returned None"
    assert np.array_equal(peeked_after_get2, frames_initial[2]), "Peek after get(2) should return the last PUT frame (F2)"
    print(f"Peek after get(2) successful, got frame with value {peeked_after_get2[0,0,0]}")

    # --- Scenario B: Put another frame, then get 1 (like get(1) without release) ---
    print("\nScenario B: put(F3), get(1)")
    frame3 = create_dummy_frames(3, 1) # F3
    assert shared_buffer.put(frame3) is True

    # Get 1 frame (gets F2, implicitly releases F0, F1 because last_get_count was 2)
    got_list_2 = shared_buffer.get(1)
    assert got_list_2 is not None, "Second get(1) failed"
    assert len(got_list_2) == 1
    assert np.array_equal(got_list_2[0], frames_initial[2:3]), "Second get(1) did not retrieve F2"

    # Peek after getting 1 (last put was F3)
    peeked_after_get1 = shared_buffer.peek_last_frame()
    assert peeked_after_get1 is not None, "Peek after get(1) returned None"
    assert np.array_equal(peeked_after_get1, frame3[0]), "Peek after get(1) should return the last PUT frame (F3)"
    print(f"Peek after get(1) successful, got frame with value {peeked_after_get1[0,0,0]}")


def test_peek_last_frame_after_get_and_release(shared_buffer):
    """Test peeking after get() with explicit release."""
    frames_initial = create_dummy_frames(10, 3) # F10, F11, F12
    assert shared_buffer.put(frames_initial) is True

    got_list = shared_buffer.get(1) # Gets F10
    assert got_list is not None
    assert np.array_equal(got_list[0], frames_initial[0:1])

    released_count = shared_buffer.release_last_got_data()
    assert released_count == 1

    peeked = shared_buffer.peek_last_frame()
    assert peeked is not None, "Peek after explicit release returned None"
    assert np.array_equal(peeked, frames_initial[2]), "Peek after explicit release should return last PUT frame (F12)"


def test_peek_last_frame_wrap_around(shared_buffer):
    """Test peeking when the write pointer has wrapped around."""
    assert shared_buffer.put(create_dummy_frames(0, 3)) is True # Puts F0, F1, F2 at indices 0, 1, 2

    got1 = shared_buffer.get(2) # Gets F0, F1. read_ptr becomes 2.
    assert got1 is not None

    released_count = shared_buffer.release_last_got_data() 
    assert released_count == 2

    assert shared_buffer.put(create_dummy_frames(3, 4)) is True

    peeked = shared_buffer.peek_last_frame()
    assert peeked is not None, "Peek after wrap returned None"
    assert np.array_equal(peeked, create_dummy_frames(6, 1)[0]), "Peek after wrap returned incorrect frame"


# Helper function for the concurrent peeker task
def _concurrent_peek_task(buffer_or_source, duration, results_queue, stop_event, use_process=False):
    """Target function for the peeker thread/process."""
    buffer = None
    peeked_values = []
    try:
        if use_process:
            buffer = ProcessSafeSharedRingBuffer(create=False, source_buffer=buffer_or_source)
        else:
            buffer = buffer_or_source

        start_time = time.time()
        while not stop_event.is_set() and time.time() - start_time < duration:
            peeked_frame = buffer.peek_last_frame()
            if peeked_frame is not None:
                if peeked_frame.shape == FRAME_SHAPE:
                     value = peeked_frame[0, 0, 0]
                     peeked_values.append(value)
                else:
                     print(f"Warning: Peeked frame had unexpected shape {peeked_frame.shape}")
                     peeked_values.append(f"ErrorShape:{peeked_frame.shape}")
            else:
                peeked_values.append(None)
            time.sleep(0.01)

        results_queue.put({'type': 'peek', 'values': peeked_values})

    except Exception as e:
        print(f"{'Process' if use_process else 'Thread'} Peek Task Error: {e}")
        results_queue.put({'type': 'peek', 'values': peeked_values, 'error': e})
    finally:
        if use_process and buffer:
            try:
                buffer.close()
            except Exception as close_e:
                 print(f"Error closing buffer in peek task: {close_e}")


def _concurrent_put_task_returning_values(buffer_or_source, duration, frame_shape, frame_dtype, result_queue, producer_finished_event, start_value_offset=0):
    """Producer task that returns the list of values put."""
    buffer = None
    put_values = []
    frame_counter = 0
    try:
        buffer = ProcessSafeSharedRingBuffer(create=False, source_buffer=buffer_or_source)
        start_time = time.time()
        while time.time() - start_time < duration:
            value_to_put = (start_value_offset + frame_counter) % 256
            frame = create_dummy_frames(value_to_put, 1, shape=frame_shape, dtype=frame_dtype)
            if buffer.put(frame, timeout=1.0):
                put_values.append(value_to_put)
                frame_counter += 1
            else:
                pass
        result_queue.put({'type': 'put', 'values': put_values})
    except Exception as e:
        print(f"Producer Task Error: {e}")
        result_queue.put({'type': 'put', 'values': put_values, 'error': e})
    finally:
        producer_finished_event.set()
        if buffer:
             try:
                 buffer.close()
             except Exception as close_e:
                  print(f"Error closing buffer in put task: {close_e}")


def _concurrent_get_task_returning_values(buffer_or_source, duration, frame_shape, frame_dtype, result_queue, producer_finished_event):
    """Consumer task that returns the list of values retrieved."""
    buffer = None
    retrieved_values = []
    try:
        buffer = ProcessSafeSharedRingBuffer(create=False, source_buffer=buffer_or_source)
        while not producer_finished_event.is_set() or buffer.unread_count > 0:
            frames_list = buffer.get(1, timeout=0.1)
            if frames_list:
                retrieved_frame = frames_list[0][0]
                if retrieved_frame.shape == frame_shape:
                     value = retrieved_frame[0, 0, 0]
                     retrieved_values.append(value)
                else:
                     print(f"Warning: Got frame had unexpected shape {retrieved_frame.shape}")
                     retrieved_values.append(f"ErrorShape:{retrieved_frame.shape}")

            elif producer_finished_event.is_set():
                 break

        result_queue.put({'type': 'get', 'values': retrieved_values})
    except Exception as e:
        print(f"Consumer Task Error: {e}")
        result_queue.put({'type': 'get', 'values': retrieved_values, 'error': e})
    finally:
        if buffer:
             try:
                 buffer.close()
             except Exception as close_e:
                  print(f"Error closing buffer in get task: {close_e}")


def test_peek_last_frame_concurrent(shared_buffer):
    """
    Tests peek_last_frame concurrently with put and get operations using processes.
    """
    mp.set_start_method('spawn', force=True)

    test_duration = 3.0 # seconds
    num_producers = 1
    num_consumers = 1
    num_peekers = 1

    producer_results_queue = mp.Queue()
    consumer_results_queue = mp.Queue()
    peeker_results_queue = mp.Queue()
    producer_finished_event = mp.Event()
    stop_peeking_event = mp.Event()

    processes = []

    for i in range(num_producers):
        p = mp.Process(target=_concurrent_put_task_returning_values,
                       args=(shared_buffer, test_duration, FRAME_SHAPE, FRAME_DTYPE, producer_results_queue, producer_finished_event, i * 1000))
        processes.append(p)
        p.start()

    for _ in range(num_consumers):
        c = mp.Process(target=_concurrent_get_task_returning_values,
                       args=(shared_buffer, test_duration, FRAME_SHAPE, FRAME_DTYPE, consumer_results_queue, producer_finished_event))
        processes.append(c)
        c.start()

    for _ in range(num_peekers):
        pk = mp.Process(target=_concurrent_peek_task,
                        args=(shared_buffer, test_duration, peeker_results_queue, stop_peeking_event, True))
        processes.append(pk)
        pk.start()

    time.sleep(test_duration + 0.5)
    stop_peeking_event.set()

    put_results_data = producer_results_queue.get(timeout=5.0)
    put_values = put_results_data.get('values', [])
    if put_results_data.get('error'): print(f"Producer Error reported: {put_results_data['error']}")

    consumed_results_data = consumer_results_queue.get(timeout=5.0)
    consumed_values = consumed_results_data.get('values', [])
    if consumed_results_data.get('error'): print(f"Consumer Error reported: {consumed_results_data['error']}")

    peeked_results_all = []
    for _ in range(num_peekers):
         peeker_data = peeker_results_queue.get(timeout=5.0)
         peeked_results_all.append(peeker_data.get('values', []))
         if peeker_data.get('error'): print(f"Peeker Error reported: {peeker_data['error']}")

    for p in processes:
        p.join(timeout=5.0)
        if p.is_alive():
             print(f"Warning: Process {p.name} (pid {p.pid}) did not terminate gracefully. Terminating.")
             p.terminate()
             p.join(timeout=1.0)

    print(f"\nConcurrent Peek Test: Total put values: {len(put_values)}")
    print(f"Concurrent Peek Test: Total consumed values: {len(consumed_values)}")

    put_value_set = set(put_values)
    all_peeked_values_flat = [val for peeker_list in peeked_results_all for val in peeker_list]
    all_peeked_values_flat_valid = [val for peeker_list in peeked_results_all for val in peeker_list if val is not None and not isinstance(val, str)]

    print(f"Concurrent Peek Test: Total peeked returns: {len(all_peeked_values_flat)}")
    print(f"Concurrent Peek Test: Total valid peeked values: {len(all_peeked_values_flat_valid)}")

    invalid_peeks = 0
    for peeked_val in all_peeked_values_flat_valid:
        if peeked_val not in put_value_set:
            invalid_peeks += 1

    allowed_invalid_ratio = 0.01
    if len(all_peeked_values_flat_valid) > 0:
         assert invalid_peeks / len(all_peeked_values_flat_valid) <= allowed_invalid_ratio, \
             f"Found {invalid_peeks}/{len(all_peeked_values_flat_valid)} peeked values not present in the set of put values."
    else:
         print("Warning: No valid values were peeked during the concurrent test.")
         assert len(put_values) > 0, "Concurrent test put 0 values."

    print("\nConcurrent peek test finished.")


import random
import cProfile
import pstats
import io
import threading
import queue

def profiled_worker(target_func, *args, **kwargs):
    pr = cProfile.Profile()
    pr.enable()
    target_func(*args, **kwargs)
    pr.disable()
    s = io.StringIO()
    ps = pstats.Stats(pr, stream=s).sort_stats('cumulative')
    ps.print_stats()
    print("\n=== Detailed Call Analysis for Target Function ===")
    print(s.getvalue())

def stress_producer_task(source_buffer, duration, frame_shape, frame_dtype, results_queue, producer_finished_event):
    """Task for a stress test producer process."""
    try:
        buffer = ProcessSafeSharedRingBuffer(create=False, source_buffer=source_buffer)
        start_time = time.time()
        frame_count = 0
        while time.time() - start_time < duration:
            num_frames_to_put = random.randint(1, BUFFER_CAPACITY//2)
            frames = create_dummy_frames(frame_count, num_frames_to_put, shape=frame_shape, dtype=frame_dtype, use_random=True)
            if buffer.put(frames, timeout=1.0):
                frame_count += num_frames_to_put
            else:
                pass
        results_queue.put(frame_count)
    except Exception as e:
        print(f"Stress Producer process error: {e}")
        raise
    finally:
        producer_finished_event.set()
        buffer.close()

def stress_consumer_task(source_buffer, duration, frame_shape, frame_dtype, results_queue, producer_finished_event):
    """Task for a stress test consumer process."""
    try:
        buffer = ProcessSafeSharedRingBuffer(create=False, source_buffer=source_buffer)
        start_time = time.time()
        retrieved_frames = []
        retrieved_count = 0
        while not producer_finished_event.is_set() or buffer.unread_count > 0:
            num_frames_to_get = random.randint(1, BUFFER_CAPACITY//2)
            frames_list = buffer.get(num_frames_to_get, timeout=0.1)

            if frames_list is not None:
                for frames in frames_list:
                    retrieved_frames.append(frames.copy())
                    retrieved_count += frames.shape[0]

        results_queue.put((retrieved_frames, retrieved_count))
    except Exception as e:
        print(f"Stress Consumer process error: {e}")
        raise
    finally:
        print(f"Stress Consumer process finished, retrieved {retrieved_count} frames")
        buffer.close()

def test_process_safety_stress(shared_buffer):
    """Test concurrent put and get operations from multiple processes under stress."""
    print("In test_process_safety_stress, Starting stress test...")
    mp.set_start_method('spawn', force=True)

    test_duration = 5 # seconds

    producer_results_queue = mp.Queue(maxsize=2)
    consumer_results_queue = mp.Queue(maxsize=2)

    producer_finished_event = mp.Event()

    producer_p = mp.Process(target=stress_producer_task, args=(shared_buffer, test_duration, FRAME_SHAPE, FRAME_DTYPE, producer_results_queue, producer_finished_event))
    consumer_p = mp.Process(target=stress_consumer_task, args=(shared_buffer, test_duration, FRAME_SHAPE, FRAME_DTYPE, consumer_results_queue, producer_finished_event))

    producer_p.start()
    consumer_p.start()

    total_produced = producer_results_queue.get()
    retrieved_frames_list, total_retrieved = consumer_results_queue.get()

    producer_p.join()
    consumer_p.join()

    print(f"Stress Test: Total frames produced: {total_produced}")
    print(f"Stress Test: Total frames retrieved: {total_retrieved}")
    print(f"Performance: {total_retrieved / test_duration} fps")

    assert total_produced == total_retrieved, f"Stress Test Failed: Produced {total_produced} frames, but retrieved {total_retrieved}"

    expected_frames = create_dummy_frames(0, total_produced, shape=FRAME_SHAPE, dtype=FRAME_DTYPE, use_random=True)
    retrieved_frames = np.concatenate(retrieved_frames_list, axis=0, dtype=FRAME_DTYPE)
    assert np.array_equal(retrieved_frames, expected_frames), "Stress Test Failed: Retrieved frame sequence does not match expected sequence"


def test_deadlock_after_full_get(shared_buffer):
    """
    Test for deadlock scenario after buffer is fully put and then fully retrieved.
    """
    frames_to_put_initial = create_dummy_frames(0, BUFFER_CAPACITY)
    assert shared_buffer.put(frames_to_put_initial) is True, "Initial put to fill buffer failed"

    retrieved_frames_list = shared_buffer.get(BUFFER_CAPACITY)
    assert retrieved_frames_list is not None, "Initial get of all frames failed"
    retrieved_frames = np.concatenate(retrieved_frames_list, axis=0)
    assert len(retrieved_frames) == BUFFER_CAPACITY
    assert np.array_equal(retrieved_frames, frames_to_put_initial)

    timeout_get_result = shared_buffer.get(1, timeout=0.1)
    assert timeout_get_result is None, "Timed-out get did not return None as expected"

    frame_to_put_after_release = create_dummy_frames(BUFFER_CAPACITY, 1)
    put_after_release_success = shared_buffer.put(frame_to_put_after_release, timeout=0.1)
    assert put_after_release_success is True, "Put after space release failed"

    get_after_put_result_list = shared_buffer.get(1, timeout=0.1)
    assert get_after_put_result_list is not None, "Get after putting new frame failed"
    assert len(get_after_put_result_list) == 1
    get_after_put_result = get_after_put_result_list[0]
    assert np.array_equal(get_after_put_result, frame_to_put_after_release)

    print("\nDeadlock scenario test passed.")


def _concurrent_put_task(buffer_or_source, frame_to_put, result_queue, use_process=False):
    """Target function for the put thread/process."""
    buffer = None
    try:
        if use_process:
            buffer = ProcessSafeSharedRingBuffer(create=False, source_buffer=buffer_or_source)
        else:
            buffer = buffer_or_source

        put_success = buffer.put(frame_to_put, timeout=2.0)
        result_queue.put({'type': 'put', 'success': put_success})
    except Exception as e:
        print(f"{'Process' if use_process else 'Thread'} Put Task Error: {e}")
        result_queue.put({'type': 'put', 'success': False, 'error': e})
    finally:
        if use_process and buffer:
            buffer.close()


def _concurrent_get_task(buffer_or_source, result_queue, use_process=False):
    """Target function for the get thread/process."""
    buffer = None
    try:
        if use_process:
            buffer = ProcessSafeSharedRingBuffer(create=False, source_buffer=buffer_or_source)
        else:
            buffer = buffer_or_source

        get_result_list = buffer.get(1, timeout=2.0)

        if get_result_list:
            retrieved_frame = np.concatenate(get_result_list, axis=0).copy()
            result_queue.put({'type': 'get', 'frame': retrieved_frame})
        else:
            result_queue.put({'type': 'get', 'frame': None})
    except Exception as e:
        print(f"{'Process' if use_process else 'Thread'} Get Task Error: {e}")
        result_queue.put({'type': 'get', 'frame': None, 'error': e})
    finally:
        if use_process and buffer:
            buffer.close()


def test_concurrent_put_get_multithread(shared_buffer):
    """Tests concurrent put and get using threads."""
    frames_to_put_initial = create_dummy_frames(0, BUFFER_CAPACITY)
    assert shared_buffer.put(frames_to_put_initial) is True

    retrieved_frames_list = shared_buffer.get(BUFFER_CAPACITY)
    assert retrieved_frames_list is not None
    assert len(np.concatenate(retrieved_frames_list, axis=0)) == BUFFER_CAPACITY

    frame_to_put_concurrently = create_dummy_frames(BUFFER_CAPACITY, 1)
    results_queue = queue.Queue()

    get_thread = threading.Thread(target=_concurrent_get_task, args=(shared_buffer, results_queue, False))
    get_thread.start()

    time.sleep(0.2)
    assert results_queue.empty(), "Get thread returned prematurely before put"

    put_thread = threading.Thread(target=_concurrent_put_task, args=(shared_buffer, frame_to_put_concurrently, results_queue, False))
    put_thread.start()

    get_thread.join(timeout=5.0)
    put_thread.join(timeout=5.0)

    assert not get_thread.is_alive()
    assert not put_thread.is_alive()

    results = {}
    while not results_queue.empty():
        item = results_queue.get()
        results[item['type']] = item

    assert 'put' in results
    assert results['put'].get('success') is True
    assert 'get' in results
    assert results['get'].get('frame') is not None
    assert np.array_equal(results['get']['frame'], frame_to_put_concurrently)
    print("\nConcurrent put/get multithread test passed.")


def test_concurrent_put_get_multiprocess(shared_buffer):
    """Tests concurrent put and get using processes."""
    mp.set_start_method('spawn', force=True)

    frames_to_put_initial = create_dummy_frames(0, BUFFER_CAPACITY)
    assert shared_buffer.put(frames_to_put_initial) is True

    retrieved_frames_list = shared_buffer.get(BUFFER_CAPACITY)
    assert retrieved_frames_list is not None
    assert len(np.concatenate(retrieved_frames_list, axis=0)) == BUFFER_CAPACITY

    frame_to_put_concurrently = create_dummy_frames(BUFFER_CAPACITY, 1)
    results_queue = mp.Queue()

    get_process = mp.Process(target=_concurrent_get_task, args=(shared_buffer, results_queue, True))
    get_process.start()

    time.sleep(0.2)
    assert results_queue.empty()

    put_process = mp.Process(target=_concurrent_put_task, args=(shared_buffer, frame_to_put_concurrently, results_queue, True))
    put_process.start()

    get_process.join(timeout=5.0)
    put_process.join(timeout=5.0)

    assert not get_process.is_alive()
    assert not put_process.is_alive()

    results = {}
    while not results_queue.empty():
        try:
            item = results_queue.get(timeout=0.1)
            results[item['type']] = item
        except queue.Empty:
            break

    assert 'put' in results
    assert results['put'].get('success') is True
    assert 'get' in results
    assert results['get'].get('frame') is not None
    assert np.array_equal(results['get']['frame'], frame_to_put_concurrently)
    print("\nConcurrent put/get multiprocess test passed.")


# =============================================================================
# New v2a pickle-specific tests
# =============================================================================

def test_pickle_protocol_direct(shared_buffer):
    """
    Directly exercises __getstate__ and __setstate__ to verify the blacklist
    protocol without going through pickle.dumps/loads.

    Why not pickle.dumps?
        mp.Lock / mp.Condition invoke context.assert_spawning(self) during
        pickling, which raises RuntimeError unless we are inside a spawn context
        (i.e. mp.Process is actively creating a child). The real DI use-case
        — passing the buffer as an mp.Process arg — DOES work (see
        test_pickle_multiprocess_producer_consumer). This test validates the
        __getstate__ / __setstate__ logic independently of that restriction.

    Checks:
        1. __getstate__ blacklist: _metadata_ctypes removed, SHMs → name strings.
        2. __setstate__ restoration: SHMs re-attached, _metadata_ctypes rebuilt.
        3. Python attributes (_buffer_capacity, _frame_shape, _dtype …) preserved.
        4. Functional: write via original, read via restored object.
    """
    # --- 1. Verify __getstate__ output ---
    state = shared_buffer.__getstate__()

    # _metadata_ctypes must be absent (process-local memory binding)
    assert '_metadata_ctypes' not in state, \
        "_metadata_ctypes must be removed by __getstate__ (process-local binding)"

    # SharedMemory objects must be replaced with their name strings
    assert isinstance(state['_metadata_shm'], str), \
        "_metadata_shm must be a name string in the pickled state"
    assert isinstance(state['_data_shm'], str), \
        "_data_shm must be a name string in the pickled state"
    assert state['_metadata_shm'] == shared_buffer.metadata_name
    assert state['_data_shm']     == shared_buffer.data_name

    # Pure Python attributes must pass through untouched
    assert state['_buffer_capacity'] == shared_buffer._buffer_capacity
    assert state['_frame_shape']     == shared_buffer._frame_shape
    assert state['_frame_bytes']     == shared_buffer._frame_bytes
    assert state['_data_buffer_size'] == shared_buffer._data_buffer_size
    # (dtype is wrapped in np.dtype, check via equality)
    assert np.dtype(state['_dtype']) == shared_buffer._dtype

    # --- 2. Call __setstate__ directly on a blank object ---
    restored = ProcessSafeSharedRingBuffer.__new__(ProcessSafeSharedRingBuffer)
    restored.__setstate__(state)

    # --- 3. Verify restored attributes ---
    assert restored._buffer_capacity  == shared_buffer._buffer_capacity
    assert restored._frame_shape      == shared_buffer._frame_shape
    assert restored._dtype            == shared_buffer._dtype
    assert restored._frame_bytes      == shared_buffer._frame_bytes
    assert restored._data_buffer_size == shared_buffer._data_buffer_size

    # ctypes must have been rebuilt (not None or missing)
    assert restored._metadata_ctypes is not None, \
        "_metadata_ctypes must be rebuilt by __setstate__"

    # SharedMemory objects must be re-attached and point to the same segments
    assert restored._metadata_shm is not None
    assert restored._data_shm     is not None
    assert restored._metadata_shm.name == shared_buffer.metadata_name
    assert restored._data_shm.name     == shared_buffer.data_name

    # Lock / Condition must be the same objects (passed through as-is)
    assert restored._pointer_lock  is shared_buffer._pointer_lock
    assert restored._data_available  is shared_buffer._data_available
    assert restored._space_available is shared_buffer._space_available

    # --- 4. Functional verification: write via original, read via restored ---
    frame = create_dummy_frames(42, 1)
    assert shared_buffer.put(frame) is True, "put via original buffer failed"
    frames_list = restored.get(1, timeout=2.0)
    assert frames_list is not None, "get via restored buffer returned None"
    assert np.array_equal(
        np.concatenate(frames_list, axis=0), frame
    ), "frame content mismatch after __getstate__/__setstate__ roundtrip"

    restored.close()
    print("\nPickle protocol direct (__getstate__/__setstate__) test passed.")


# Helper tasks that use the pickled buffer DIRECTLY (no create=False)
def _pickle_producer_task(buffer: ProcessSafeSharedRingBuffer, num_frames: int,
                           frame_shape, frame_dtype):
    """
    Producer that receives the buffer already re-attached via pickle (__setstate__).
    Does NOT call create=False — this is the key difference from the legacy helper.
    """
    try:
        for i in range(num_frames):
            frames = create_dummy_frames(i, 1, shape=frame_shape, dtype=frame_dtype)
            if not buffer.put(frames, timeout=10.0):
                print(f"_pickle_producer_task: Timeout putting frame {i}")
                break
    except Exception as e:
        print(f"_pickle_producer_task error: {e}")
        raise
    finally:
        buffer.close()


def _pickle_consumer_task(buffer: ProcessSafeSharedRingBuffer, num_frames: int,
                           frame_shape, frame_dtype, results_queue):
    """
    Consumer that receives the buffer already re-attached via pickle (__setstate__).
    Does NOT call create=False.
    """
    retrieved_frames = []
    try:
        for i in range(num_frames):
            frames_list = buffer.get(1, timeout=10.0)
            if frames_list is not None:
                retrieved_frames.append(np.concatenate(frames_list, axis=0).copy())
            else:
                print(f"_pickle_consumer_task: Timeout getting frame {i}")
                break
        results_queue.put(retrieved_frames)
    except Exception as e:
        print(f"_pickle_consumer_task error: {e}")
        raise
    finally:
        buffer.close()


def test_pickle_multiprocess_producer_consumer(shared_buffer):
    """
    Verifies that a buffer created in the main process can be passed directly
    to child processes as mp.Process args (which triggers pickle), without any
    manual create=False re-attachment call.

    This is the core DI use-case enabled by v2a's pickle protocol.
    """
    mp.set_start_method('spawn', force=True)

    num_frames = BUFFER_CAPACITY * 2
    results_queue = mp.Queue(maxsize=1)

    # Pass shared_buffer directly — mp.Process will pickle it via __getstate__,
    # and the child will receive a fully functional buffer via __setstate__.
    producer_p = mp.Process(
        target=_pickle_producer_task,
        args=(shared_buffer, num_frames, FRAME_SHAPE, FRAME_DTYPE),
        name="PickleProducer",
    )
    consumer_p = mp.Process(
        target=_pickle_consumer_task,
        args=(shared_buffer, num_frames, FRAME_SHAPE, FRAME_DTYPE, results_queue),
        name="PickleConsumer",
    )

    producer_p.start()
    consumer_p.start()

    retrieved_frames_list = results_queue.get(timeout=60)
    retrieved_frames = np.concatenate(retrieved_frames_list, axis=0)

    producer_p.join(timeout=15)
    consumer_p.join(timeout=15)

    if producer_p.is_alive():
        producer_p.terminate()
    if consumer_p.is_alive():
        consumer_p.terminate()

    assert len(retrieved_frames) == num_frames, \
        f"Expected {num_frames} frames via pickle DI, got {len(retrieved_frames)}"

    expected_frames = create_dummy_frames(0, num_frames, shape=FRAME_SHAPE, dtype=FRAME_DTYPE)
    retrieved_set = set(frame.tobytes() for frame in retrieved_frames)
    expected_set  = set(frame.tobytes() for frame in expected_frames)
    assert retrieved_set == expected_set, \
        "Pickle DI multiprocess test: retrieved frame set does not match expected"

    print("\nPickle multiprocess producer/consumer test passed.")


def test_pickle_attach_mode_backward_compat(shared_buffer):
    """
    Verifies that the deprecated create=False attach mode still works correctly,
    ensuring backward compatibility with code that uses the old API.
    """
    # Use the old create=False API explicitly
    attached = ProcessSafeSharedRingBuffer(create=False, source_buffer=shared_buffer)

    frame = create_dummy_frames(99, 1)
    assert shared_buffer.put(frame) is True, "put via original buffer failed"

    frames_list = attached.get(1, timeout=2.0)
    assert frames_list is not None, "get via attach-mode buffer returned None"
    assert np.array_equal(
        np.concatenate(frames_list, axis=0), frame
    ), "frame content mismatch via deprecated attach mode"

    # Also verify peek works through the attached buffer
    frame2 = create_dummy_frames(88, 1)
    assert shared_buffer.put(frame2) is True
    peeked = attached.peek_last_frame()
    assert peeked is not None, "peek_last_frame via attached buffer returned None"
    assert np.array_equal(peeked, frame2[0]), "peek content mismatch via attach mode"

    attached.close()
    print("\nDeprecated attach mode backward compatibility test passed.")
