# Provide service of SAM2RT inference using flask
# This code is primarily generated by google-gemini-2.5-flash with cline, without careful review.
# Some API details may be modified later.

# /track_frame: receive image and return the tracking result (coordinates of center?)
# /prompt_frame: receive image and prompt for tracking initialization, return the mask result (coordinates of center?)

# /ready: return the status of the service, if ready, return 200, else return 500, and the message of the error, if any.

import os
import numpy as np
import torch
import cv2
import base64
import json # For parsing JSON strings from multipart/form-data
import threading
import queue
import uuid # To generate unique request IDs
import time # For debugging/logging

from flask import Flask, request, jsonify

from sam2.build_sam import build_sam2_camera_predictor

app = Flask(__name__)

# Global worker instance
worker = None

# Global variables to store SAM2 predictor and the ID of the currently tracked object
# These will now be managed within the PredictorWorker
# predictor = None
# current_obj_id = None # Stores the obj_id currently being tracked
# consecutive_lost_frames = 0 # Counter for consecutive frames where tracking is lost
# TRACK_LOST_WARNING_THRESHOLD = 5 # Threshold for warning about lost tracking

# Model configuration
# These paths are relative to the project root.
# Since sam2rt_remote_service.py is in 'notebooks/', we need to go up one level.
SAM2_CHECKPOINT = "../../SAM2/checkpoints/sam2.1_hiera_small.pt"
MODEL_CFG = "../sam2/configs/sam2.1/sam2.1_hiera_s_vos.yaml"

# Model configuration
# These paths are relative to the project root.
# Since sam2rt_remote_service.py is in 'notebooks/', we need to go up one level.
SAM2_CHECKPOINT = "../../SAM2/checkpoints/sam2.1_hiera_small.pt"
MODEL_CFG = "../sam2/configs/sam2.1/sam2.1_hiera_s_vos.yaml"

class PredictorWorker(threading.Thread):
    def __init__(self, model_cfg, sam2_checkpoint):
        super().__init__()
        self.model_cfg = model_cfg
        self.sam2_checkpoint = sam2_checkpoint
        self.input_queue = queue.Queue()
        self.output_queues = {} # Dictionary to hold per-request output queues
        self.predictor = None
        self.current_obj_id = None
        self.consecutive_lost_frames = 0
        self.TRACK_LOST_WARNING_THRESHOLD = 5
        self.stop_event = threading.Event()

    def initialize_predictor_internal(self):
        if self.predictor is None:
            print("Worker: Initializing SAM2 predictor...")
            if not torch.cuda.is_available():
                raise RuntimeError("CUDA is not available. Please ensure a CUDA-enabled GPU is present.")
            
            script_dir = os.path.dirname(__file__)
            abs_sam2_checkpoint = os.path.join(script_dir, self.sam2_checkpoint)
            abs_model_cfg = os.path.join(script_dir, self.model_cfg)

            if not os.path.exists(abs_sam2_checkpoint):
                raise FileNotFoundError(f"Worker: SAM2 checkpoint file not found: {abs_sam2_checkpoint}")
            if not os.path.exists(abs_model_cfg):
                raise FileNotFoundError(f"Worker: Model configuration file not found: {abs_model_cfg}")

            self.predictor = build_sam2_camera_predictor(abs_model_cfg, abs_sam2_checkpoint, vos_optimized=True).to("cuda")
            print("Worker: SAM2 predictor initialized.")

    def _process_prompt_task(self, frame, prompt_data):
        obj_id = prompt_data.get("obj_id")
        points = np.array(prompt_data.get("points", []), dtype=np.float32)
        labels = np.array(prompt_data.get("labels", []), dtype=np.int32)

        if points.size == 0 or labels.size == 0 or obj_id is None:
            return {"status": "failure", "message": "Prompt points, labels or obj_id are empty/missing"}
        
        self.predictor.load_first_frame(frame)
        _, out_obj_ids, out_mask_logits = self.predictor.add_new_prompt(
            frame_idx=0,
            obj_id=obj_id,
            points=points,
            labels=labels,
        )
        processed_mask = (out_mask_logits > 0.0).cpu().to(torch.uint8).numpy()
        mask_info = get_mask_info(processed_mask[0].squeeze())

        if not mask_info:
            print(f"Worker: SAM returned empty mask for obj_id {obj_id}")
            self.current_obj_id = None
            return {"status": "failure", "tracked_objects": {}, "message": "SAM returned empty mask, initialization failed"}
        else:
            self.current_obj_id = obj_id
            self.consecutive_lost_frames = 0
            mask_to_encode = processed_mask[0].squeeze() * 255
            _, buffer = cv2.imencode(".png", mask_to_encode)
            mask_image_bytes = buffer.tobytes()
            mask_image_b64 = base64.b64encode(mask_image_bytes).decode("utf-8")
            return {
                "status": "success", 
                "tracked_objects": {
                    str(obj_id): {
                        "mask_info": mask_info,
                        "mask_image_png_b64": mask_image_b64
                    }
                }
            }

    def _process_track_task(self, frame):
        if self.predictor is None or self.current_obj_id is None:
            return {"status": "failure", "message": "Predictor not initialized or no object is being tracked. Please call /prompt_frame first."}
        else:
            print(f"Worker: Before track: CUDA memory allocated: {torch.cuda.memory_allocated() / (1024**2):.2f} MB, cached: {torch.cuda.memory_reserved() / (1024**2):.2f} MB")
            out_obj_ids, out_mask_logits = self.predictor.track(frame)
            print(f"Worker: After track: CUDA memory allocated: {torch.cuda.memory_allocated() / (1024**2):.2f} MB, cached: {torch.cuda.memory_reserved() / (1024**2):.2f} MB")

            processed_mask = (out_mask_logits > 0.0).cpu().to(torch.uint8).numpy()
            mask_info = get_mask_info(processed_mask[0].squeeze())

            if not mask_info:
                self.consecutive_lost_frames += 1
                print(f"Worker: SAM returned empty mask for obj_id {self.current_obj_id}. Consecutive lost frames: {self.consecutive_lost_frames}")
                if self.consecutive_lost_frames >= self.TRACK_LOST_WARNING_THRESHOLD:
                    print(f"Worker: WARNING: Tracking for obj_id {self.current_obj_id} has been lost for {self.consecutive_lost_frames} consecutive frames. Re-prompting might be needed.")
                return {"status": "warning", "tracked_objects": {}, "obj_id": 0, "message": f"SAM returned empty mask, tracking lost for {self.consecutive_lost_frames} consecutive frames"}
            else:
                self.consecutive_lost_frames = 0
                mask_to_encode = processed_mask[0].squeeze() * 255
                _, buffer = cv2.imencode(".png", mask_to_encode)
                mask_image_bytes = buffer.tobytes()
                mask_image_b64 = base64.b64encode(mask_image_bytes).decode("utf-8")
                return {
                    "status": "success", 
                    "tracked_objects": {
                        str(self.current_obj_id): {
                            "mask_info": mask_info,
                            "mask_image_png_b64": mask_image_b64
                        }
                    }
                }

    def run(self):
        with torch.autocast(device_type="cuda", dtype=torch.bfloat16):
            with torch.inference_mode():
                self.initialize_predictor_internal()
                while not self.stop_event.is_set():
                    try:
                        task = self.input_queue.get(timeout=0.1)
                        task_type = task["type"]
                        request_id = task["request_id"]
                        frame = task["frame"]
                        response_queue = self.output_queues[request_id]

                        result = {}
                        if task_type == "prompt":
                            result = self._process_prompt_task(frame, task["prompt_data"])
                        elif task_type == "track":
                            result = self._process_track_task(frame)
                        
                        response_queue.put(result)
                        self.input_queue.task_done()
                    except queue.Empty:
                        continue
                    except Exception as e:
                        print(f"Worker: Error processing task: {e}")
                        if request_id in self.output_queues:
                            self.output_queues[request_id].put({"status": "failure", "message": str(e)})
                        self.input_queue.task_done()

    def stop(self):
        self.stop_event.set()
        self.join() # Wait for the thread to finish

def get_mask_info(mask_array):
    """
    Extracts center point and/or bounding box information from a binary mask array.
    mask_array should be a (H, W) boolean or uint8 array.
    """
    if not np.any(mask_array):
        return {} # Empty mask

    # Ensure mask is boolean type
    mask_bool = mask_array > 0

    # Get coordinates of all non-zero points
    coords = np.argwhere(mask_bool) # (N, 2) format, (row, col) i.e. (y, x)

    if coords.shape[0] == 0:
        return {} # Re-check, just in case

    # Calculate bounding box
    y_min, x_min = coords.min(axis=0)
    y_max, x_max = coords.max(axis=0)
    bbox = [int(x_min), int(y_min), int(x_max), int(y_max)] # [x_min, y_min, x_max, y_max]

    # Calculate center point (centroid)
    M = cv2.moments(mask_array.astype(np.uint8))
    if M["m00"] != 0:
        cX = int(M["m10"] / M["m00"])
        cY = int(M["m01"] / M["m00"])
        center = [cX, cY] # [x, y]
    else:
        # If M["m00"] is 0, it means the mask area is 0 (empty mask), already handled above.
        # Can return an empty list or handle as needed.
        center = [] 

    return {"bbox": bbox, "center": center}

@app.route("/ready", methods=["GET"])
def check_ready():
    global worker
    if worker and worker.predictor is not None:
        return jsonify({"status": "ready"}), 200
    else:
        return jsonify({"status": "not_ready"}), 503

@app.route("/prompt_frame", methods=["POST"])
def prompt_frame():
    global worker
    try:
        # Check if image file is present in the request
        if 'image' not in request.files:
            return jsonify({"status": "failure", "message": "No image file provided"}), 400
        
        image_file = request.files['image']
        if image_file.filename == '':
            return jsonify({"status": "failure", "message": "No selected image file"}), 400

        # Read image data
        img_bytes = image_file.read()
        np_arr = np.frombuffer(img_bytes, np.uint8)
        frame = cv2.imdecode(np_arr, cv2.IMREAD_COLOR)
        print(type(frame), frame.shape, frame.dtype)
        if frame is None:
            return jsonify({"status": "failure", "message": "Could not decode image"}), 400
        
        # Save the received frame for inspection (optional, can remove later)
        cv2.imwrite("received_prompt_frame.jpg", frame)
        print("Saved received_prompt_frame.jpg")

        # Get prompt data from form field
        prompt_json_str = request.form.get('prompt')
        if not prompt_json_str:
            return jsonify({"status": "failure", "message": "No prompt data provided"}), 400
        
        try:
            prompt_data = json.loads(prompt_json_str)
        except json.JSONDecodeError:
            return jsonify({"status": "failure", "message": "Invalid prompt JSON format"}), 400

        # Generate a unique request ID
        request_id = str(uuid.uuid4())
        response_queue = queue.Queue(maxsize=1) # Create a dedicated queue for this request's response
        worker.output_queues[request_id] = response_queue

        # Put task into worker's input queue
        worker.input_queue.put({
            "type": "prompt",
            "request_id": request_id,
            "frame": frame,
            "prompt_data": prompt_data
        })

        # Wait for response from worker
        result = response_queue.get(timeout=60) # Add a timeout
        del worker.output_queues[request_id] # Clean up the response queue

        return jsonify(result)

    except Exception as e:
        print(f"Error in prompt_frame: {e}")
        return jsonify({"status": "failure", "message": str(e)}), 500

@app.route("/track_frame", methods=["POST"])
def track_frame():
    global worker
    try:
        # Check if image file is present in the request
        if 'image' not in request.files:
            return jsonify({"status": "failure", "message": "No image file provided"}), 400
        
        image_file = request.files['image']
        if image_file.filename == '':
            return jsonify({"status": "failure", "message": "No selected image file"}), 400

        # Read image data
        img_bytes = image_file.read()
        np_arr = np.frombuffer(img_bytes, np.uint8)
        frame = cv2.imdecode(np_arr, cv2.IMREAD_COLOR)
        print(type(frame), frame.shape, frame.dtype)
        if frame is None:
            return jsonify({"status": "failure", "message": "Could not decode image"}), 400

        # Save the received frame for inspection (optional, can remove later)
        cv2.imwrite("received_track_frame.jpg", frame)
        print("Saved received_track_frame.jpg")

        # Check if worker is initialized and an object is being tracked (worker will handle this internally)
        if worker is None:
            return jsonify({"status": "failure", "message": "Predictor worker not initialized."}), 400
        
        # Generate a unique request ID
        request_id = str(uuid.uuid4())
        response_queue = queue.Queue(maxsize=1)
        worker.output_queues[request_id] = response_queue

        # Put task into worker's input queue
        worker.input_queue.put({
            "type": "track",
            "request_id": request_id,
            "frame": frame
        })

        # Wait for response from worker
        result = response_queue.get(timeout=60) # Add a timeout
        del worker.output_queues[request_id] # Clean up the response queue

        return jsonify(result)

    except Exception as e:
        print(f"Error in track_frame: {e}")
        return jsonify({"status": "failure", "message": str(e)}), 500

if __name__ == "__main__":
    # Initialize the predictor worker before starting the Flask application
    try:
        worker = PredictorWorker(MODEL_CFG, SAM2_CHECKPOINT)
        worker.start() # Start the worker thread
        
        # Listen on all network interfaces, port 5000
        app.run(host="0.0.0.0", port=5000, debug=False)
    except Exception as e:
        print(f"Failed to start Flask service: {e}")
    finally:
        if worker:
            worker.stop() # Ensure worker thread is stopped on exit
